/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.librarymanagementsystem;
import java.io.*;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
//import javax.swing.text.Document;
/**
 *
 * @author aaush
 */
public class NewJFrame5 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame5
     */
    public NewJFrame5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Algerian", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("delete Book from record");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(366, 19, 369, 33);

        jButton2.setFont(new java.awt.Font("Algerian", 2, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 0, 51));
        jButton2.setText("SEE Student DATA by  aadhaar no.");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(560, 61, 324, 26);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(323, 65, 158, 22);

        jLabel2.setFont(new java.awt.Font("Algerian", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(32, 238, 83, 24);

        jLabel3.setFont(new java.awt.Font("Algerian", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("nationality");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(14, 307, 120, 24);

        jLabel4.setFont(new java.awt.Font("Algerian", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("gender");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(21, 357, 80, 24);

        jLabel5.setFont(new java.awt.Font("Algerian", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("email");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(32, 411, 54, 24);

        jLabel6.setFont(new java.awt.Font("Algerian", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("mobilenumber");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(326, 180, 140, 24);

        jLabel7.setFont(new java.awt.Font("Algerian", 2, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("Address");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(326, 238, 110, 24);

        jLabel8.setFont(new java.awt.Font("Algerian", 2, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("issue date");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(320, 307, 140, 24);

        jLabel10.setFont(new java.awt.Font("Algerian", 2, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setText("BookName");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(320, 380, 120, 24);

        jLabel11.setFont(new java.awt.Font("Algerian", 2, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jLabel11.setText("booknumber");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(663, 180, 140, 24);

        jLabel12.setFont(new java.awt.Font("Algerian", 2, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setText("price");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(654, 229, 70, 24);

        jLabel13.setFont(new java.awt.Font("Algerian", 2, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setText("No.of days");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(655, 279, 140, 24);

        jLabel14.setFont(new java.awt.Font("Algerian", 2, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 0, 0));
        jLabel14.setText("total");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(646, 357, 90, 24);

        jLabel15.setFont(new java.awt.Font("Algerian", 2, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 0, 0));
        jLabel15.setText("AADHAR NO.");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(32, 188, 107, 24);

        jTextField2.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(jTextField2);
        jTextField2.setBounds(171, 177, 71, 22);

        jTextField3.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(jTextField3);
        jTextField3.setBounds(171, 235, 71, 22);

        jTextField4.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(jTextField4);
        jTextField4.setBounds(171, 304, 71, 22);

        jTextField5.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(jTextField5);
        jTextField5.setBounds(171, 354, 71, 22);

        jTextField6.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(jTextField6);
        jTextField6.setBounds(171, 408, 71, 22);

        jTextField7.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(jTextField7);
        jTextField7.setBounds(517, 177, 71, 22);

        jTextField8.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(jTextField8);
        jTextField8.setBounds(517, 235, 71, 22);

        jTextField9.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(jTextField9);
        jTextField9.setBounds(517, 304, 90, 22);

        jTextField11.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(jTextField11);
        jTextField11.setBounds(510, 370, 77, 22);
        getContentPane().add(jTextField12);
        jTextField12.setBounds(840, 177, 77, 22);
        getContentPane().add(jTextField13);
        jTextField13.setBounds(840, 226, 77, 22);
        getContentPane().add(jTextField14);
        jTextField14.setBounds(840, 276, 77, 22);
        getContentPane().add(jTextField15);
        jTextField15.setBounds(840, 354, 77, 22);

        jButton1.setFont(new java.awt.Font("Algerian", 2, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 51));
        jButton1.setText("DELETE THIS Student RECORDS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(560, 99, 324, 26);

        jButton3.setFont(new java.awt.Font("Algerian", 3, 18)); // NOI18N
        jButton3.setText("SEE ALL OPTIONS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(670, 440, 230, 31);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/librarymanagementsystem/sylvia-yang-_ar2ENzmqb0-unsplash.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(-43, -4, 1190, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try{   
        Class.forName("com.mysql.jdbc.Driver");
       Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/crud","root","");
       PreparedStatement a = conn.prepareStatement("select idproofs,name,nationality,gender,email,mobilenumber,address,issuedate,bookname,booknumber,price,bookingdays,total from allotebook where idproofs = ?");
      int id = Integer.parseInt(jTextField1.getText());
      a.setInt(1,id);
       ResultSet rs = a.executeQuery();
        if(rs.next()==false)
        {
            JOptionPane.showMessageDialog(this, "SORRY RECORD IS NOT FOUND !!!"); 
            jTextField2.setText(" ");
             jTextField3.setText(" ");
              jTextField4.setText(" ");
               jTextField5.setText(" ");
                jTextField6.setText(" ");
                 jTextField7.setText(" ");
                  jTextField8.setText(" ");
                   jTextField9.setText(" ");
                  
             jTextField11.setText(" ");
              jTextField12.setText(" ");
               jTextField13.setText(" ");
                jTextField14.setText(" ");
                 jTextField15.setText(" ");           
        }
        else {
             jTextField2.setText(rs.getString("idproofs"));
             jTextField3.setText(rs.getString("name"));
              jTextField4.setText(rs.getString("nationality"));
               jTextField5.setText(rs.getString("gender"));
                jTextField6.setText(rs.getString("email"));
                 jTextField7.setText(rs.getString("mobilenumber"));
                  jTextField8.setText(rs.getString("address"));
                   jTextField9.setText(rs.getString("issuedate"));
                    
             jTextField11.setText(rs.getString("bookname"));
              jTextField12.setText(rs.getString("booknumber"));
               jTextField13.setText(rs.getString("price"));
                jTextField14.setText(rs.getString("bookingdays"));
                 jTextField15.setText(rs.getString("total"));  
        
        }
     }  catch (Exception e) {
           JOptionPane.showMessageDialog(this, e);
        }       // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
aadhaar = jTextField1.getText();
try{
Class.forName("com.mysql.jdbc.Driver");
Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/crud","root","");
String sql = "Delete from allotebook Where idproofs = "+aadhaar;
PreparedStatement a = conn.prepareStatement(sql);
a.executeUpdate();
JOptionPane.showMessageDialog(this,"DATA IS REMOVED SUCCESSFULLY !!!");
conn.close();
}
catch(Exception e){
JOptionPane.showMessageDialog(this, e);
}


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 NewJFrame1 jf1 = new NewJFrame1();
       jf1.show();
       dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
private String aadhaar;
}
